Portfolio desktop branch
H-Ramalan/portfolio-desktop pull request #1
Opened 2023-05-12 09:55 UTC by H-Ramalan

•	Set up linters files: Configured ESLint, Hint, and Stylelint to ensure consistent code formatting and catch any potential syntax errors.
•	Added markup with styling: I added semantic HTML markup and CSS styling to improve the visual appeal and accessibility of the project.
•	Used Gitflow: Following the Gitflow branching model to ensure a structured workflow for the project and to make collaboration with other developers more efficient.
Kindly help review and let me know if any further modifications are needed.

Thank you for your review.

2023-05-12 10:05 UTC, AbelG101 reviewed
![](https://media.giphy.com/media/PkFYci8BUkmdA7K1qa/giphy.gif)

# Hi STUDENT_MENTION 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- You have submitted a project, that doesn't have a running linter check. So please make sure you configured the appropriate linters which [you can find here](https://github.com/microverseinc/linters-config/tree/master/html-css)
  ![firefox_jggpKyxfkV](https://github.com/H-Ramalan/portfolio-desktop/assets/104968236/2a4506e8-fa64-43e4-ad81-019bde7b8378)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-05-12 11:57 UTC, divinecharlotte requested changes
Hi @H-Ramalan    , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## To Highlight 💯 
-Descriptive commit messages👍
- linters are passing 👍 




 
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️

_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-12 11:57 UTC, divinecharlotte commented on style.css
> +@media screen and (max-width: 768px) {
- [ ] kindly consider enclosing all the desktop version CSS in this`@media screen and (min-width: 768px) {}` media query as you did here on the mobile version  to make your code more organized and make sure that this requirement is full filled 
> Use media queries in your CSS file to make your desktop version look like the template you selected `(Desktop: >=768px).`

2023-05-12 11:57 UTC, divinecharlotte commented on style.css
> +  color: orange;
- [ ] Kindly consider sticking to the Figma design as much as possible by giving these icons the same color as the one given in the design the reason is to make your project an exact duplicate of the given one check the screenshots below to see the difference 
- your design 👇 
<img width="1262" alt="Screen Shot 2023-05-12 at 13 50 22" src="https://github.com/H-Ramalan/portfolio-desktop/assets/60146030/4a5c117e-c01f-45cf-9eda-c4c338ba7dee">



- Figma design 👇 
<img width="704" alt="Screen Shot 2023-05-12 at 13 50 47" src="https://github.com/H-Ramalan/portfolio-desktop/assets/60146030/db6ddec9-5e41-4149-8c5a-de5b489ad4fa">

2023-05-13 00:05 UTC, Efiamotu-1 approved these changes
Hi @H-Ramalan , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# STATUS: APPROVED 🕺🥳 

![giphy](https://user-images.githubusercontent.com/89055502/234114221-4ca295de-fd8f-4af6-9c49-a6d4c6ea67f7.gif)


## Highlights :dart: 
* Correct GitHub flow :heavy_check_mark: 
* All linters passing :heavy_check_mark: 
* Good PR summary :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, you can now Merge since it is Approved ✅, However if there are any conflicts please resolve them before merging.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-13 00:05 UTC, Efiamotu-1 commented on index.html
[OPTIONAL]
- [ ] please it is a project requirement that your mobile version stays correct as much as your desktop version however from the screen below of your header and about section it is visible that the background images are not displaying as they should on mobile. i kundly suggest that you fix this design error :+1: :sparkles: 
- your designs header & about section
![bg-h](https://github.com/H-Ramalan/portfolio-desktop/assets/89055502/c05e903f-3f6a-4cf1-beaa-7369def61e10)
![bg-ab](https://github.com/H-Ramalan/portfolio-desktop/assets/89055502/d704fa53-5767-4fe6-aafe-9dec1681d102)

2023-05-13 00:05 UTC, Efiamotu-1 commented on index.html
[OPTIONAL]
- [ ] you currently do not have enough spaciing between your content and the border of your toolbar section, please kindly add the necessary spacing on desktop version so it matches correctly the figma design as shown below :+1: 
- [ ] Also you making use of the word `my logo` as your logo, but you can alternatively put in your name which is more descriptive and professional to use :+1: :grin: :sparkles: 
- figma design
![logo](https://github.com/H-Ramalan/portfolio-desktop/assets/89055502/15197d28-8696-47d6-ab31-4786f838ad50)
- your design
![logo](https://github.com/H-Ramalan/portfolio-desktop/assets/89055502/79769297-8287-498b-923d-e765d071f155)

2023-05-13 00:44 UTC, merged