Projects modal popup
H-Ramalan/portfolio-desktop pull request #5
Opened 2023-05-25 15:53 UTC by H-Ramalan

•	Set up linters files: Configured ESLint, Hint and Stylelint to ensure consistent code for-matting and catch any potential syntax errors.
•	Added markup with styling: I added semantic HTML markup and CSS styling to im-prove the visual appeal and accessibility of the project.
•	Used Gitflow: Following Gitflow branching model to ensure a structured workflow for the project and to make collaboration with other developers more efficient.
•	Implemented the modal popup functionality and created the project cards dynamically in the JavaScript file.
Kindly help review and let me know if there are any further modifications needed.
Thank you for your review.

2023-05-25 17:06 UTC, Olamarx requested changes
Hi Team, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media2.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

## Highlights
- Linters passed ✔️
- Readme file professional ✔️
- Dynamic display of data ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-25 17:06 UTC, Olamarx commented on index.html
> +          <li class="popup-list">Bootstrap</li>
- [ ] Kindly note that the data of the popup should be from the array you used for the projects you displayed dynamically. This is the requirement. So you can make it with a loop to show each card on click, it would be something more like if the data clicked is equal to the I which is from the loop, showing the content.

2023-05-25 17:06 UTC, Olamarx commented on script.js
> +    .join('')}
- [ ] I will implore you to make the buttons witdth and height for the mobile version to be as the Figma.

### Your project
![image](https://github.com/H-Ramalan/portfolio-desktop/assets/86200356/99d3feca-5e3e-4d19-919b-e5df7a19e60b)

### Figma
![image](https://github.com/H-Ramalan/portfolio-desktop/assets/86200356/53e95cd0-3c3c-4abc-ac01-4029bec612bf)

2023-05-26 14:02 UTC, ademibowale approved these changes
Hi @H-Ramalan  , 


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- When the user clicks (or taps) the button to check project details, the popup with details about the project appears.✔️
- When the user clicks (or taps) the close (X) button, the popup disappears.✔️
- The popup is responsive, it fits mobile and desktop sizes properly.✔️
- Descriptive commit messages ✔️ 
- Good use of Github flow ✔️


![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)




- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @Adebowale ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-26 14:09 UTC, merged